//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson07___Entity_Framework.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ĐTH_K22CNT1Lesson07Entities : DbContext
    {
        public ĐTH_K22CNT1Lesson07Entities()
            : base("name=ĐTH_K22CNT1Lesson07Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dthKhoa> dthKhoa { get; set; }
        public virtual DbSet<dthSV> dthSV { get; set; }
    }
}
