//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lesson07___Entity_Framework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dthSV
    {
        public string ĐthMaSV { get; set; }
        public string ĐthHoSV { get; set; }
        public string ĐthTenSV { get; set; }
        public Nullable<System.DateTime> ĐthNS { get; set; }
        public Nullable<bool> ĐthPhai { get; set; }
        public string ĐthPhone { get; set; }
        public string ĐthEmail { get; set; }
        public string ĐthID { get; set; }
    
        public virtual dthKhoa dthKhoa { get; set; }
    }
}
